# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Adding secret
      env:
        urlDB: ${{ secrets.DB_URL }}
        usernameDB: ${{ secrets.DB_USERNAME }}
        passwordDB: ${{ secrets.DB_PASSWORD }}
        uploadsPath: ${{ secrets.UPLOAD_FILES_PATH }}
        email: ${{ secrets.E_MAIL }}
        emailPassword: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        envsubst < src/main/resources/application.template.yml > src/main/resources/application.yml
        cat src/main/resources/application.yml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name : Tomcat deploy
      run: curl -v -u ${{ secrets.Username }}:${{ secrets.Password }} -T /home/runner/work/kino-cms-admin/kino-cms-admin/target/Kino_CMS_A_Rudiuk.war 'https://slj.avada-media-dev1.od.ua/manager/text/deploy?path=/Kino_CMS_A_Rudiuk'
    
